version: '3.8'

services:
  app:
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ../../../:/app
    command: uvicorn rpn_api_calculator.main:app --host 0.0.0.0 --port 8000 --reload