name: Build and Store Docker Image

on:
  push:
    branches: [ main, branch ]
  pull_request:
    branches: [ main, branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t rpn-api-calculator:latest .

    - name: Save Docker image to artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: |
          $(docker save rpn-api-calculator:latest -o rpn-api-calculator.tar) && echo rpn-api-calculator.tar
